### ISSUE TITLE
Error in new_objc_provider: Key 'linkopt' no longer supported in ObjcProvider


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_swift#1142]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3575#018ce2f8-2590-45f5-9afe-3d2cdb2e6b7d

 Platform: MacOS

 Logs: 
```(09:30:39) ERROR: /private/var/tmp/_bazel_buildkite/c8f5eeee7f112b07250892b1524f7f4f/external/_main~non_module_deps~build_bazel_rules_swift_local_config/BUILD:9:22: in xcode_swift_toolchain rule @@_main~non_module_deps~build_bazel_rules_swift_local_config//:toolchain:
Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-18/bazel-org-repo-root/rules_swift/swift/internal/xcode_swift_toolchain.bzl", line 589, column 57, in _xcode_swift_toolchain_impl
		swift_linkopts_providers = _swift_linkopts_providers(
	File "/Users/buildkite/builds/bk-imacpro-18/bazel-org-repo-root/rules_swift/swift/internal/xcode_swift_toolchain.bzl", line 257, column 51, in _swift_linkopts_providers
		objc_info = apple_common.new_objc_provider(linkopt = depset(linkopts)),
Error in new_objc_provider: Key 'linkopt' no longer supported in ObjcProvider (use CcInfo instead).
```

 Steps:
```
git clone https://github.com/bazelbuild/rules_swift.git 
git reset 7c82ef1e7e503cedb8d4c69b049e76412cc3572a --hard
export USE_BAZEL_VERSION=8e8ddaba0e90c280bfd85644d6ccd91df5b6d353
bazel build //examples/... 
```
 CC Greenteam @fweikert

**Comment by brentleyjones** [comment]
This is from `--incompatible_objc_provider_remove_linking_info` flipping in https://github.com/bazelbuild/bazel/commit/67c5c0fbf99c80aeb17073c79e8017bde443fd4b.
