### ISSUE TITLE
[Bazel CI] Error no native function or rules 'py_test'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_swift#1396]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4198#01928934-47ee-4c84-9851-b07d174a3bbb

 Platform: Ubuntu

 Logs: 
```
ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8b36565493a31e266346114e39534731/external/protobuf+/src/google/protobuf/BUILD.bazel", line 185, column 15, in <toplevel>
		staleness_test(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8b36565493a31e266346114e39534731/external/protobuf+/upb/cmake/build_defs.bzl", line 49, column 11, in staleness_test
		native.py_test(
Error: no native function or rule 'py_test'
Available attributes: action_listener, alias, available_xcodes, cc_binary, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_shared_library, cc_static_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_plugins_flag_alias, java_proto_library, java_runtime, java_test, java_toolchain, label_flag, label_setting, legacy_globals, memprof_profile, module_name, module_version, objc_import, objc_library, package, package_group, package_name, package_relative_label, platform, propeller_optimize, proto_lang_toolchain, proto_library, repo_name, repository_name, starlark_doc_extract, subpackages, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
(04:20:23) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8b36565493a31e266346114e39534731/external/protobuf+/BUILD.bazel:31:6: Target '@@protobuf+//src/google/protobuf:any_proto' contains an error and its package is in error and referenced by '@@protobuf+//:any_proto'
(04:20:23) ERROR: Analysis of target '//examples/xplatform/proto_library_group/request:request_proto' failed; build aborted: Analysis failed
(04:20:23) INFO: Elapsed time: 2.762s, Critical Path: 0.03s
(04:20:23) INFO: 1 process: 1 internal.
(04:20:23) ERROR: Build did NOT complete successfully
(04:20:23) FAILED:
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_swift
git reset 3b39bc7b36cf40fa0b451fa1af735ba2e691ee84  --hard
export USE_BAZEL_VERSION=00fdb673ba8276e83f1c821a7f93aab7038377e2
bazel build //examples/... //examples/apple/... 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
Present rules\_swift downstream CI is green  https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4221#0192bcbc-5672-4cc1-aaa9-bf227ee8e440 We are closing this issue now
