### ISSUE TITLE
swift_import fails with "new_objc_provider() missing 2 required keyword-only arguments: is_test, swift_toolchain"

### ISSUE THREAD

**Issue by pswaminathan** [bazelbuild/rules_swift#884]
```
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_p/c1a9d93c5d307e720ae1d0573bce325b/external/build_bazel_rules_swift/swift/internal/swift_import.bzl", line 90, column 26, in _swift_import_impl
		new_objc_provider(
	File "/private/var/tmp/_bazel_p/c1a9d93c5d307e720ae1d0573bce325b/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 2844, column 5, in new_objc_provider
		def new_objc_provider(
Error: new_objc_provider() missing 2 required keyword-only arguments: is_test, swift_toolchain
```

Seems to be related to #868? Looks like that added new arguments to `new_objc_provider`, but these weren't implemented in swift_import: https://github.com/bazelbuild/rules_swift/pull/868/files#diff-535d0dbea9614c6905a30dfdb0e708df3b16fc68f8930d6aba519342509dc657R2837

**Comment by keith** [comment]
@maxwellE can you investigate

**Comment by maxwellE** [comment]
Will do, I am pretty sure I know the fix
